load_module modules/ngx_http_js_module.so;
load_module modules/ngx_otel_module.so;

worker_processes auto;
error_log /dev/stderr info;

events {
}

http {
    js_engine qjs;

    include /etc/nginx/demo/http.conf;

    include /etc/nginx/mcp/mcp-njs.conf;

    server {
        listen 9000;

        include /etc/nginx/demo/mcp-server.conf;

        otel_span_attr "mcp.outcome" $mcp_outcome;
        otel_span_attr "mcp.rpc.code" $mcp_rpc_code;
        location = /mcp {
            include /etc/nginx/demo/mcp-proxy.conf;
            js_body_filter observer.observe buffer_type=buffer;
        }
    }
}
