resolver 127.0.0.11 valid=10s ipv6=off;

upstream mcp-information {
    zone mcp-information 64k;
    server mcp-information:9001 resolve;
}

upstream mcp-operations {
    zone mcp-operations 64k;
    server mcp-operations:9002 resolve;
}

upstream mcp-data {
    zone mcp-data 64k;
    server mcp-data:9003 resolve;
}
