load_module modules/ngx_otel_module.so;

worker_processes auto;
error_log /dev/stderr info;

events {
}

http {
    include /etc/nginx/demo/http.conf;

    server {
        listen 9000;

        include /etc/nginx/demo/mcp-server.conf;

        location = /mcp {
            include /etc/nginx/demo/mcp-proxy.conf;
        }
    }
}
